# Generated by Django 4.2 on 2023-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YadaFp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=350)),
                ('date', models.CharField(max_length=100)),
                ('signName', models.CharField(max_length=200)),
                ('signPhone', models.CharField(max_length=100)),
                ('signDate', models.CharField(max_length=100)),
            ],
        ),
    ]
